version: 2
jobs:
  build901:

    macos:
      xcode: "9.0.1"

    steps:
      - checkout
      - run:
          name: Build
          command: bash ./build-osx.sh

  build941:

    macos:
      xcode: "9.4.1"

    steps:
      - checkout
      - run:
          name: Build
          command: bash ./build-osx.sh

