version: 2
jobs:
  build1000:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Build
          command: bash ./build-osx.sh
      - store_artifacts:
          path: /Users/distiller/project/tdesktop/out/Debug/Telegram.app


workflows:
  version: 2
  build_and_test:
    jobs:
      - build1000
