version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
      MACOSX_DEPLOYMENT_TARGET=10.8
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: ./build-osx.sh

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test
