version: 2
jobs:
  build:

    macos901:
      xcode: "9.0.1"

    steps:
      - checkout
      - run:
          name: Build
          command: bash ./build-osx.sh

    macos941:
      xcode: "9.4.1"

    steps:
      - checkout
      - run:
          name: Build
          command: bash ./build-osx.sh

